from odmantic import Model, Field
from enum import Enum

class product_open(str, Enum):
    true = "O"
    false = "X"

class Products(Model):
    wood: product_open = Field(default="X")
    bean: product_open = Field(default="X")
    sugar: product_open = Field(default="X")
    biscket: product_open = Field(default="X")
    berry: product_open = Field(default="X")
    milk: product_open = Field(default="X")
    wool: product_open = Field(default="X")
    axe: product_open = Field(default="X")
    pickax: product_open = Field(default="X")
    saw: product_open = Field(default="X")
    shovel: product_open = Field(default="X")
    pile: product_open = Field(default="X")
    tongs: product_open = Field(default="X")
    hammer: product_open = Field(default="X")
    jellybean_jam: product_open = Field(default="X")
    sweetjelly_jam: product_open = Field(default="X")
    dalgona_jam: product_open = Field(default="X")
    pomegranate_jam: product_open = Field(default="X")
    tokberry_jam: product_open = Field(default="X")
    birddoll: product_open = Field(default="X")
    lamp: product_open = Field(default="X")
    clock: product_open = Field(default="X")
    dreamcatcher: product_open = Field(default="X")
    ryebread: product_open = Field(default="X")
    jampie: product_open = Field(default="X")
    pocachia: product_open = Field(default="X")
    donut: product_open = Field(default="X")
    castella: product_open = Field(default="X")
    croissant: product_open = Field(default="X")
    jellystew: product_open = Field(default="X")
    burger: product_open = Field(default="X")
    pasta: product_open = Field(default="X")
    omeletrice: product_open = Field(default="X")
    pizzajelly: product_open = Field(default="X")
    jellybean_meal: product_open = Field(default="X")
    flower_pot: product_open = Field(default="X")
    glass_plate: product_open = Field(default="X")
    colored_marble: product_open = Field(default="X")
    bowl: product_open = Field(default="X")
    candy_flower: product_open = Field(default="X")
    happy_flower: product_open = Field(default="X")
    flower_bundle: product_open = Field(default="X")
    flower_basket: product_open = Field(default="X")
    bouquet: product_open = Field(default="X")
    wreath: product_open = Field(default="X")
    cream: product_open = Field(default="X")
    butter: product_open = Field(default="X")
    cheese: product_open = Field(default="X")
    latte: product_open = Field(default="X")
    bubbletea: product_open = Field(default="X")
    ade: product_open = Field(default="X")
    cushion: product_open = Field(default="X")
    bearjelly_doll: product_open = Field(default="X")
    dragonfruit_dool: product_open = Field(default="X")
    root_beer: product_open = Field(default="X")
    redberry_juice: product_open = Field(default="X")
    wild_bottle: product_open = Field(default="X")
    spooky_muffin: product_open = Field(default="X")
    strawberry_cake: product_open = Field(default="X")
    chiffon_cake: product_open = Field(default="X")
    ring: product_open = Field(default="X")
    brooch: product_open = Field(default="X")
    crown: product_open = Field(default="X")
