from odmantic import Model, Field, EmbeddedModel
from typing import Optional
from enum import Enum

class product_open(str, Enum):
    true = "O"
    false = "X"

class Product_Detail(EmbeddedModel):
    supplies: product_open = Field(default="X")
    demands: product_open = Field(default="X")

class Products(Model):
    wood: Optional[Product_Detail]
    bean: Optional[Product_Detail]
    sugar: Optional[Product_Detail]
    biscuit: Optional[Product_Detail]
    berry: Optional[Product_Detail]
    milk: Optional[Product_Detail]
    wool: Optional[Product_Detail]
    axe: Optional[Product_Detail]
    pickax: Optional[Product_Detail]
    saw: Optional[Product_Detail]
    shovel: Optional[Product_Detail]
    pile: Optional[Product_Detail]
    tongs: Optional[Product_Detail]
    hammer: Optional[Product_Detail]
    jellybean_jam: Optional[Product_Detail]
    sweetjelly_jam: Optional[Product_Detail]
    dalgona_jam: Optional[Product_Detail]
    pomegranate_jam: Optional[Product_Detail]
    tokberry_jam: Optional[Product_Detail]
    birddoll: Optional[Product_Detail]
    lamp: Optional[Product_Detail]
    clock: Optional[Product_Detail]
    dreamcatcher: Optional[Product_Detail]
    ryebread: Optional[Product_Detail]
    jampie: Optional[Product_Detail]
    pocachia: Optional[Product_Detail]
    donut: Optional[Product_Detail]
    castella: Optional[Product_Detail]
    croissant: Optional[Product_Detail]
    jellystew: Optional[Product_Detail]
    burger: Optional[Product_Detail]
    pasta: Optional[Product_Detail]
    omeletrice: Optional[Product_Detail]
    pizzajelly: Optional[Product_Detail]
    jellybean_meal: Optional[Product_Detail]
    flower_pot: Optional[Product_Detail]
    glass_plate: Optional[Product_Detail]
    colored_marble: Optional[Product_Detail]
    bowl: Optional[Product_Detail]
    candy_flower: Optional[Product_Detail]
    happy_flower: Optional[Product_Detail]
    flower_bundle: Optional[Product_Detail]
    flower_basket: Optional[Product_Detail]
    bouquet: Optional[Product_Detail]
    wreath: Optional[Product_Detail]
    cream: Optional[Product_Detail]
    butter: Optional[Product_Detail]
    cheese: Optional[Product_Detail]
    latte: Optional[Product_Detail]
    bubbletea: Optional[Product_Detail]
    ade: Optional[Product_Detail]
    cushion: Optional[Product_Detail]
    bearjelly_doll: Optional[Product_Detail]
    dragonfruit_dool: Optional[Product_Detail]
    root_beer: Optional[Product_Detail]
    redberry_juice: Optional[Product_Detail]
    wild_bottle: Optional[Product_Detail]
    spooky_muffin: Optional[Product_Detail]
    strawberry_cake: Optional[Product_Detail]
    chiffon_cake: Optional[Product_Detail]
    ring: Optional[Product_Detail]
    brooch: Optional[Product_Detail]
    crown: Optional[Product_Detail]